### ISSUE TITLE
Help downloading multiple pages (Multi pages issue)

### ISSUE THREAD

**Issue by tordenver** [sixcious/downloadyze#8]
### Description

Hello,
I am trying to download the pages at the following URL without success:
https://pdfs.nycourts.gov/PeopleVs.DTrump-71543/Transcripts/4-22-2024/00001.html

I can see that the website increment each webpage. I tried the different options of increment in the multipage option of downloadyze without success. I get at the most 2 webpage downloaded. I filtered out the index page just fine.

Can you help me to get the right settings to make it work?

Thanks

### URL

https://pdfs.nycourts.gov/PeopleVs.DTrump-71543/Transcripts/4-22-2024/00001.html

### Version

0.2

### Browser

google chrome

### OS

mac os ventura

### Device

Other

**Comment by sixcious** [comment]
Hi tordenver,

I just tested this site and it worked fine on my end.
- For the Multi Action, you can use the Increment URL action and select the `00001` part with the Base Type being `Default`, or you can use the Next Link action and it should automatically find the next link based on the `next` keyword
- For the `Download Strategy`, you can use `Download the web page` and it will download the `html` files.
- Toggle on `AUTO` and set the number of `Times` (Pages to download) and `Seconds` and click `ACCEPT` to have Downloadyze start an auto downloading session.

If you still need help, attach a couple screenshots showing *all* your settings (you will most likely need to scroll the Popup Window and capture two or more screenshots).

The only issue I found is that the site employs a Cloudflare human verification check, so you'll need to verify then start Downloadyze before downloading anything. The verification check does come back after some time has elapsed and then Downloadyze won't be able to download until you re-verify, so you'll need to work around that:

![Capture](https://github.com/sixcious/downloadyze/assets/1027814/96b56227-365f-46b4-8f9a-57db2c4c7b19)

I hope this helps!

**Comment by tordenver** [comment]
Thank you Sixcious for your quick reply, I appreciate it!

I was able to download the 120 html pages after your explanations.

The verification check only came up twice... so not a big deal... but thank you for pointing it out...

Following is what I tried first... and did not work:
. I believe I first had the incrementation strategy correct.
. I used the "Download all url strategy" instead you recommended "Download the webpage" I am not sure I understand the difference between these 2 settings?
. I did not understand that "Auto" will allow you to tell Downloadyze to use what ever incremental settings to move forward. I thought validating "accept" will run the script with the settings!
. I think I understand the reasoning behind having a longer lapse of time between each download.... but would it be possible to let the user select say 2 sec. as your minimum instead of 5 sec. or do you have a specific reason for not doing so?

Some other UI comments:
. it would be nice if the "Settings" window could be extended so you could see all the settings at once
. in Google chrome, once you start Downloadyze script, Google Download popup window interfere with Downloadyze "start/stop/next" window... I could not figure out a way to move it without stopping the script... annoying...

In any case thank you for your work for this extension!

**Comment by sixcious** [comment]
Hi again tordenver, I'm glad you got it working and thank you for the kind feedback and questions! 💜

> I used the "Download all url strategy" instead you recommended "Download the webpage" I am not sure I understand the difference between these 2 settings?

Yes, so "All URLs" will download all the URLs (links) *found* on the page. This is what most people usually want to do, but for that website you posted, that would only download those "Prev" and "Next" links found on the page (not the actual page itself).

> I did not understand that "Auto" will allow you to tell Downloadyze to use what ever incremental settings to move forward. I thought validating "accept" will run the script with the settings!

Yes, Multi working automatically is the common use case so I can understand how you expected that. I wanted to allow users to also use Multi without Auto so they could manually pick which pages to download (admittedly, a less common use case). I can change it to toggle that Auto Switch on by default when you change to Multi Page to make it more accommodating to the more common use case. 👍 

> I think I understand the reasoning behind having a longer lapse of time between each download.... but would it be possible to let the user select say 2 sec. as your minimum instead of 5 sec. or do you have a specific reason for not doing so?

I might allow the Seconds to be lowered, but maybe only as a special/premium option to keep it from being abused by everyone. Experience has shown me that many users don't read the warnings or understand the ramifications and I really don't want a deluge of people getting IP banned or [429'd](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) (and/or angry website owners!).

> it would be nice if the "Settings" window could be extended so you could see all the settings at once

Agreed! Unfortunately, the browsers limit the popup window to a size of 800 x 600 px. One alternative would be to not use a popup and open up another OS window, but then you would have to switch back and forth between two windows (which may not make for the best UX!).

> in Google chrome, once you start Downloadyze script, Google Download popup window interfere with Downloadyze "start/stop/next" window... I could not figure out a way to move it without stopping the script... annoying...

This might depend on the version of Chrome you're using, but I know they recently introduced a new way of showing download notifications that show up in the top-right download icon instead of in the bottom tray. I know for me I don't seem to have any issues by having both of the below settings unchecked via the following Download Settings URL:
`chrome://settings/downloads`
- `Ask where to save each file before downloading`
- `Show downloads when they're done`

Thanks again!

**Comment by tordenver** [comment]
Thanks for your details reply Sixcious.

> > I used the "Download all url strategy" instead you recommended "Download the webpage" I am not sure I understand the difference between these 2 settings?
> 
> Yes, so "All URLs" will download all the URLs (links) _found_ on the page. This is what most people usually want to do, but for that website you posted, that would only download those "Prev" and "Next" links found on the page (not the actual page itself).

Ok now I understand better.

> 
> > I did not understand that "Auto" will allow you to tell Downloadyze to use what ever incremental settings to move forward. I thought validating "accept" will run the script with the settings!
> 
> Yes, Multi working automatically is the common use case so I can understand how you expected that. I wanted to allow users to also use Multi without Auto so they could manually pick which pages to download (admittedly, a less common use case). I can change it to toggle that Auto Switch on by default when you change to Multi Page to make it more accommodating to the more common use case. 👍

Yes I think it is more of a User Interface issue than anything else. To me mixing settings and "running" your extension should be separated somehow.

> 
> > I think I understand the reasoning behind having a longer lapse of time between each download.... but would it be possible to let the user select say 2 sec. as your minimum instead of 5 sec. or do you have a specific reason for not doing so?
> 
> I might allow the Seconds to be lowered, but maybe only as a special/premium option to keep it from being abused by everyone. Experience has shown me that many users don't read the warnings or understand the ramifications and I really don't want a deluge of people getting IP banned or [429'd](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) (and/or angry website owners!).

Obviously you know more than I do about consequences and repercussions of website download and I was not aware that it could trigger some other issues like you mention.

> 
> > it would be nice if the "Settings" window could be extended so you could see all the settings at once
> 
> Agreed! Unfortunately, the browsers limit the popup window to a size of 800 x 600 px. One alternative would be to not use a popup and open up another OS window, but then you would have to switch back and forth between two windows (which may not make for the best UX!).

Again limitations that I was not aware from the host browser. I understand your choices.

> 
> > in Google chrome, once you start Downloadyze script, Google Download popup window interfere with Downloadyze "start/stop/next" window... I could not figure out a way to move it without stopping the script... annoying...
> 
> This might depend on the version of Chrome you're using, but I know they recently introduced a new way of showing download notifications that show up in the top-right download icon instead of in the bottom tray. I know for me I don't seem to have any issues by having both of the below settings unchecked via the following Download Settings URL: `chrome://settings/downloads`

For your info if it helps I am using Chrome Version 124.0.6367.78 (Official Build) (×86_64) on Mac OS Ventura.
I turn off the settings as well. Will see if it helps.

Thank you.
